### ISSUE TITLE
Incompatible on server

### ISSUE THREAD

**Issue by PowfuArras** [CleanroomMC/NeverEnoughAnimation#9]
The mod is incompatible on the server. It doesn't just do nothing, it actively crashes the game.
This log specifically is in a pack with other mods, but I am able to reproduce this with only mixinbooter and neverenoughanimation.

It would be convenient to have the mod do nothing rather than needing to remove it, as I and others use junctions or symlinks to automatically sync mods and configs between the server and client.

> [10:09:20] [main/WARN] [mixin]: Error loading class: net/minecraft/client/Minecraft (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3f857e08 from coremod FMLCorePlugin)
[10:09:20] [main/FATAL] [Foundation]: Unable to launch
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at top.outlands.foundation.LaunchHandler.launch(LaunchHandler.java:119) [LaunchHandler.class:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at top.outlands.foundation.boot.Foundation.main(Foundation.java:41) [foundation-0.13.8.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [cleanroom-0.2.2-alpha+build.14.run.652.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [cleanroom-0.2.2-alpha+build.14.run.652.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/inventory/Container
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3572) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3777) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2452) ~[?:?]
        at net.minecraft.entity.EntityList.register(EntityList.java:410) ~[vi.class:?]
        at net.minecraft.entity.EntityList.init(EntityList.java:317) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.register(Bootstrap.java:505) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.inventory.Container
        at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:259) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.8.jar:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3572) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3777) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2452) ~[?:?]
        at net.minecraft.entity.EntityList.register(EntityList.java:410) ~[vi.class:?]
        at net.minecraft.entity.EntityList.init(EntityList.java:317) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.register(Bootstrap.java:505) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:406) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:55) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$1(TransformerDelegate.java:150) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.runTransformers(ActualClassLoader.java:331) ~[foundation-0.13.8.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:68) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:243) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.8.jar:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3572) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3777) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2452) ~[?:?]
        at net.minecraft.entity.EntityList.register(EntityList.java:410) ~[vi.class:?]
        at net.minecraft.entity.EntityList.init(EntityList.java:317) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.register(Bootstrap.java:505) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        ... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for mixin.neverenoughanimations.json:ContainerMixin from mod unknown-owner during activity: [Transform -> Method slotClick(IILnet/minecraft/inventory/ClickType;Lnet/minecraft/entity/player/EntityPlayer;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/llamalad7/mixinextras/sugar/ref/LocalRef;)V -> INVOKESTATIC -> net/minecraft/client/Minecraft::func_71410_x:()Lnet/minecraft/client/Minecraft;]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1290) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:55) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$1(TransformerDelegate.java:150) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.runTransformers(ActualClassLoader.java:331) ~[foundation-0.13.8.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:68) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:243) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.8.jar:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3572) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3777) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2452) ~[?:?]
        at net.minecraft.entity.EntityList.register(EntityList.java:410) ~[vi.class:?]
        at net.minecraft.entity.EntityList.init(EntityList.java:317) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.register(Bootstrap.java:505) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        ... 9 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1290) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:55) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$1(TransformerDelegate.java:150) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.runTransformers(ActualClassLoader.java:331) ~[foundation-0.13.8.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:68) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:243) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.8.jar:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3572) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3777) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2452) ~[?:?]
        at net.minecraft.entity.EntityList.register(EntityList.java:410) ~[vi.class:?]
        at net.minecraft.entity.EntityList.init(EntityList.java:317) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.register(Bootstrap.java:505) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:772) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:738) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1290) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:55) ~[sponge-mixin-0.19.7+mixin.0.8.5.jar:0.19.7+mixin.0.8.5]
        at top.outlands.foundation.TransformerDelegate.lambda$fillTransformerHolder$1(TransformerDelegate.java:150) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.runTransformers(ActualClassLoader.java:331) ~[foundation-0.13.8.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:68) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.findClass(ActualClassLoader.java:243) ~[foundation-0.13.8.jar:?]
        at top.outlands.foundation.boot.ActualClassLoader.loadClass(ActualClassLoader.java:266) ~[foundation-0.13.8.jar:?]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:3572) ~[?:?]
        at java.lang.Class.getConstructor0(Class.java:3777) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2452) ~[?:?]
        at net.minecraft.entity.EntityList.register(EntityList.java:410) ~[vi.class:?]
        at net.minecraft.entity.EntityList.init(EntityList.java:317) ~[vi.class:?]
        at net.minecraft.init.Bootstrap.register(Bootstrap.java:505) ~[ni.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1470) ~[MinecraftServer.class:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        ... 9 more

**Comment by brachy84** [comment]
This is a client side mod. It shouldnt do anything on the server.

**Comment by PowfuArras** [comment]
I agree, it shouldn't do anything. The issue is that the server crashes with the mod enabled, rather than just doing nothing.
